### ISSUE TITLE
可以增加香港学校吗?

### ISSUE THREAD

**Issue by KiritoHugh** [Smlight/CSYuTuiMian2019#4]
[香港科技大学(HKUST)PhD提前招生](https://mp.weixin.qq.com/s?srcid=&scene=23&sharer_sharetime=1563800313256&mid=2247484335&sharer_shareid=0e4f18fca8920468231c30daecc44bc5&sn=a1a4268d7727889bb76de8d953bb6230&idx=1&__biz=MzI5MjMyMjA0Mg%3D%3D&chksm=ec026c3adb75e52c79e5e4d6161b8950ed13ae3c7a590f22f8e6234ddc66a96fc0d52faeb30e&mpshare=1#rd)

报名时间: 7月23-8月31
面试:

- 北京 8月31
- 上海 9月7
- 深圳 9月14

**Comment by GrayXu** [comment]
申请HK系的PhD的流程和预推免完全不同呀。。

**Comment by Smlight** [comment]
抱歉，我也认为流程很不一样……
